### ISSUE TITLE
Error with large count: bit offset is not an integer or out of range

### ISSUE THREAD

**Issue by e271828-** [erikdubbelboer/redis-lua-scaling-bloom-filter#12]
I'd like to have a bloom filter with a count of several billion. 

However, with values above ~420,000,000 I get this error:
@user_script:81: ERR bit offset is not an integer or out of range

I've implemented a sharding scheme for my own purposes, but perhaps it should be auto-sharding behind the scenes? 

Either way, the maximum size and performance implications should probably be documented.

**Comment by erikdubbelboer** [comment]
Are you using a layered or a normal filter?

**Comment by erikdubbelboer** [comment]
The issue is that redis only supports 31 bit numbers as indexes to SETBIT.

For a quick calculation see: https://play.golang.org/p/Z79EGVdm_y

I should definitely document this somewhere.

**Comment by e271828-** [comment]
Thanks, realized the core issue is actually that redis strings max out at 4 gigabits. This was with a normal filter.

**Comment by posix4e** [comment]
I believe this is good to close
