### ISSUE TITLE
bloom:count incorrect after reload from dump

### ISSUE THREAD

**Issue by e271828-** [erikdubbelboer/redis-lua-scaling-bloom-filter#13]
I loaded about two billion strings into sharded bloom filters, then dumped the database and loaded it on another machine.

On the first machine the result of:

`redis-cli KEYS '*:count' | xargs -IREPLACE redis-cli GET "REPLACE" | paste -s -d+ | bc`

was correct, while on the second machine it reported about 43 million. 

However, the bloom filters work correctly when tested against a random subset of the two billion strings.

**Comment by erikdubbelboer** [comment]
What method did you use to dump and load it into another machine?

**Comment by e271828-** [comment]
Copied across the `dump.rdb`.

**Comment by erikdubbelboer** [comment]
That should work. If it didn't I suggest making an issue with https://github.com/antirez/redis as this has nothing to do with the bloom filter.
