### ISSUE TITLE
Unable to add and check for string with special characters

### ISSUE THREAD

**Issue by Prebid-Vertoz** [erikdubbelboer/redis-lua-scaling-bloom-filter#16]
Hi guys,
     First of all, I would like to thank you for providing this excellent data structure for redis. Previously, we are storing the alphanumeric string. In that case, it's working perfect. But, now we need to store the alphanumeric string with special characters. However, these string with special character gets stored in bloom filter, but, whenever checking for that particular string, it's always returning false.

      Example, 
          Case 1 : 7c1663ed4f54dbab  (Working)
          Case 2 : mBCPNjXUkOoU7jILeXPUxQ==  (Not working)

 Please, help me to resolve this issue or let me know, whether it is the limitation of this bloom filter.

**Comment by erikdubbelboer** [comment]
I just tried this myself and everything works fine. What client library are you using? Could it be that the library isn't encoding the strings correctly for the redis protocol?

I'm trying to push a commit which changes the testing to use lots of different characters but the Github issues seem to prevent me from pushing at the moment.

**Comment by erikdubbelboer** [comment]
See: https://github.com/erikdubbelboer/redis-lua-scaling-bloom-filter/commit/9040e3230df4eac9c5710f27c04c6eda238bd8b7

**Comment by Prebid-Vertoz** [comment]
Yes erikdubbelboer, you are right. There is a problem with the encoding technique. Now, it's working fine. Thank you for your quick response.
