### ISSUE TITLE
Missleading documentation

### ISSUE THREAD

**Issue by starinacool** [erikdubbelboer/redis-lua-scaling-bloom-filter#6]
In the readme:
"cas.lua will return 1 if the element is added, 0 otherwise."

But cas return 0 if element not in the filter and 1 otherwise.

**Comment by erikdubbelboer** [comment]
You are right, it's fixed now. Thanks.

**Comment by starinacool** [comment]
Thank you for such a good implementation. I'm using it in production. cas is great.
By the ways, the same wrong description is in the cas.lua header comments.

**Comment by erikdubbelboer** [comment]
Thanks. Also fixed in `cas.lua`.
