### ISSUE TITLE
Possible typo in README

### ISSUE THREAD

**Issue by lukeasrodgers** [erikdubbelboer/redis-lua-scaling-bloom-filter#9]
Hi, I'm wondering if this line from the README is a typo: "`cas.lua` does a Check And Set, this will not add the element if it doesn't already exist".

From reviewing the code, it looks like `cas.lua` **_will_** add the element if it doesn't already exist; or, put differently, it will not add the element if it already exists.

Apologies if my understanding is incorrect.

**Comment by erikdubbelboer** [comment]
You are right. I have fixed it. Thanks.
